### PR TITLE
Update to Eigen 3.4

### PR DESCRIPTION
**Pull request by SteveBronder**
# Description

This is based on #23 and just copy pastes Eigen 3.4

Fixes # (issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes (`pytest`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Update version number (should this be 1.2 since it's a dependency bump?)

### CODE REVIEW

**Comment by fruzsinaagocs** [comment]
Thank you for this PR!

Some tests fail with 
```
pyoscode/_pyoscode.hpp:6:10: fatal error: Eigen/Dense: No such file or directory
6 | #include <Eigen/Dense>
  |          ^~~~~~~~~~~~~
```
Re version number, I think we could bump to 1.2.0.

**Comment by fruzsinaagocs** [comment]
I'm unable to run the workflow now with the error message `[Invalid workflow file: .github/workflows/python-package.yml#L28](https://github.com/fruzsinaagocs/oscode/actions/runs/5416101385/workflow)
The workflow is not valid. .github/workflows/python-package.yml (Line: 28, Col: 9): 'with' is already defined`

**Comment by SteveBronder** [comment]
Yes I'm debugging this right now my bad

**Comment by SteveBronder** [comment]
Just updated versio #! If tests pass then I think we are good to go!

**Pull request merged**
